### PR TITLE
Merge `release/26.5` into `project/chat-modernization`

### PR DESCRIPTION
**Pull request by rohvani**
## Description

This PR merges the changes from `release/26.5` into `project/chat-modernization`.

---

## Checklist

Please ensure the following before requesting review:

- [ ] I have provided a clear title and detailed description for this pull request.
- [ ] If useful, I have included media such as screenshots and video to show off my changes.
- [ ] The PR is linked to a relevant issue with sufficient context.
- [ ] I have tested the changes locally and verified they work as intended.
- [ ] All new and existing tests pass.
- [ ] Code follows the project's style guidelines.
- [ ] Documentation has been updated if needed.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have reviewed the [contributing guidelines](https://github.com/secondlife/viewer/blob/develop/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by Geenz — APPROVED** [review]

**Comment by Geenz** [comment]
@rohvani Looks like the macOS build is failing - potentially a redefinition of handleRequestResolutionUpdate.  Reads as a bad merge.  Clean that up, let it get through CI/CD, and I think we'll be good.
